### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by SVH-Powel** [BobTheShoplifter/HomeAssistant-Posten#15]
I get the following error in the log and the integration is not updating its sensors

`Denne feilen stammer fra en tilpasset integrasjon.

Logger: homeassistant
Source: custom_components/posten/binary_sensor.py:38
Integration: Når kommer Posten (documentation, issues)
First occurred: 2. mai 2023 kl. 20:54:28 (11 occurrences)
Last logged: 06:54:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 341, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 401, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
    nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'
`

**Comment by BobTheShoplifter** [comment]
Kan det hende postnummeret et ugyldig?
________________________________
From: Stig Vidar Hovland ***@***.***>
Sent: Wednesday, May 3, 2023 7:01:19 AM
To: BobTheShoplifter/HomeAssistant-Posten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BobTheShoplifter/HomeAssistant-Posten] AttributeError: 'list' object has no attribute 'get' (Issue #15)


I get the following error in the log and the integration is not updating its sensors

`Denne feilen stammer fra en tilpasset integrasjon.

Logger: homeassistant
Source: custom_components/posten/binary_sensor.py:38
Integration: Når kommer Posten (documentation, issues)
First occurred: 2. mai 2023 kl. 20:54:28 (11 occurrences)
Last logged: 06:54:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 341, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 401, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/binary_sensor/init.py", line 211, in state
if (is_on := self.is_on) is None:
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'
`

**Comment by SVH-Powel** [comment]
![image](https://user-images.githubusercontent.com/64255194/235837838-0a95e0b5-d91e-4926-bec1-c0cde6acfe40.png)

https://adressesok.posten.no/postal_codes/search?q=4353



![image](https://user-images.githubusercontent.com/64255194/235838316-f32bd4b5-071e-4357-b31f-ca6bca836080.png)

**Comment by SVH-Powel** [comment]
Stusser litt på at disse to har samme id, men det er kanskje ikke noe problem......

![image](https://user-images.githubusercontent.com/64255194/235838919-e17180e6-1a9d-453a-a35b-d0e0665ca475.png)

**Comment by BobTheShoplifter** [comment]
Her spør jeg @ludeeus 😅 Det som er litt rart er jo at det ser ut som dataen er der?

**Comment by BobTheShoplifter** [comment]
Kan se ut som et problem med binary_sensor faktisk, ser at den aldri har vært ON hos meg etter patchen

**Comment by ludeeus** [comment]
Jeg gjetter på at token ikke er korrekt, kanskje det mangler en oppdatering.
Hvis du ikke har token returnerer API `[]` (list) istedenfor `{'delivery_dates': []}` (dictionary)
1. Oppdater hvis det ikke er gjort.
2. Koden kan endres til å sjekke om data er korrekt før bruk.

**Comment by ludeeus** [comment]
For ID, det forventet at de har den samme, det er kun ett problem hvis 2 enheter under samme domenet (sensor fks.) har samme ID, her er det 1 sensor og en binary_sensor. Det er ikke noe problem.

**Comment by bengtdg** [comment]
Har samme problemer her ser det ut til. Slettet integrasjonen, og la den til påny. 
Da får jeg bare opp en device uten entities. 
Og følgende dukker opp i loggen:
`Logger: homeassistant.components.sensor
Source: custom_components/posten/sensor.py:31
Integration: Sensor (documentation, issues)
First occurred: 4:00:08 AM (14 occurrences)
Last logged: 8:57:11 AM

Error adding entities for domain sensor with platform posten
Error while setting up posten platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 653, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/sensor.py", line 31, in icon
    nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'
`

OPPDATERING :
Etter en restart så finner den de 3 entitiene som skal være der, og det ser ut til å fungere greit... Men Har utfordringer med at den ikke oppdaterer seg skikkelig fra dag til dag.

**Comment by BobTheShoplifter** [comment]
Skal være fiksa nå!

Plz teste så skal jeg justere dersom det ikke fungerer!
