### ISSUE TITLE
Sensor utilgjengelig

### ISSUE THREAD

**Issue by BMK4560** [BobTheShoplifter/HomeAssistant-Posten#5]
Sensor er utilgjengelig

**Comment by BMK4560** [comment]
Error fetching information from https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=7000 - 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=7000')

**Comment by eriklysoe** [comment]
Same here after upgrade to 2023.2.5

2023-02-16 20:37:42.733 ERROR (MainThread) [custom_components.posten] Error fetching information from https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=1623 - 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=1623')

**Comment by feddiriko** [comment]
Samme her etter oppdatering til 2023.2.5

First occurred: 21:12:37 (1 occurrences) 
Last logged: 21:12:37

Error fetching information from https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=4051 - 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=4044')

**Comment by BobTheShoplifter** [comment]
Oh my, any idea why this is happening now?

**Comment by eriklysoe** [comment]
Error decoding json, and they have updated:

Update orjson to resolve segmentation fault during JSON serialisation ([@mgjbroadbent](https://github.com/mgjbroadbent) - [#88119](https://github.com/home-assistant/core/pull/88119))

I have no coding skills, just a wild guess 😅

**Comment by BobTheShoplifter** [comment]
Yeah, just saw the same but it seems to be posten returning html, looking into it now

**Comment by BobTheShoplifter** [comment]
I might have a fix, testing now!

**Comment by BobTheShoplifter** [comment]
https://github.com/BobTheShoplifter/HomeAssistant-Posten/releases/tag/v0.1.2 should fix it, update via hacs!

**Comment by mikke49** [comment]
That fixed it. Excellent work, thank you!

**Comment by eriklysoe** [comment]
Great, thanks!

**Comment by jorlarsen** [comment]
After updating to newest version, I still didnt get any values to the sensor. Tried to remove it and install it again, now I dont have any entities, only an empty device.

**Comment by BobTheShoplifter** [comment]
Hmm, ill try debugging more. Its working for me atm

**Comment by SumMarius** [comment]
2023-02-17 14:09:48.262 ERROR (MainThread) [custom_components.posten] Error fetching information from https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/5?postCode=1622 - 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/5?postCode=1622')
2023-02-17 14:09:48.728 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform posten
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 639, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/binary_sensor.py", line 44, in icon
    nextdelivery = self.coordinator.data.get("nextDeliveryDays")
AttributeError: 'NoneType' object has no attribute 'get'
2023-02-17 14:09:48.732 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform posten
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 639, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/sensor.py", line 30, in icon
    nextdelivery = self.coordinator.data.get("nextDeliveryDays")
AttributeError: 'NoneType' object has no attribute 'get'
2023-02-17 14:09:48.775 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.nextDeliveryDays }}'
2023-02-17 14:09:48.904 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up posten platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 639, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/binary_sensor.py", line 44, in icon
    nextdelivery = self.coordinator.data.get("nextDeliveryDays")
AttributeError: 'NoneType' object has no attribute 'get'
2023-02-17 14:09:48.911 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up posten platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 639, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/sensor.py", line 30, in icon
    nextdelivery = self.coordinator.data.get("nextDeliveryDays")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by BobTheShoplifter** [comment]
Siste versjon? Tror muligens utviklerne til posten driver å kødder med oss ;(

**Comment by BobTheShoplifter** [comment]
Aha i see, posten har lagd apiet slik at det er et tilfeldig tall hver dag
https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/9?postCode=xxxx 5 i går, i dag 9. Skal finne ut hvordan de finner ut hva som er "dagens" tall

**Comment by BobTheShoplifter** [comment]
Aha, det er ikke random men html seksjoner. Om jeg endrer til 9 så funker det igjen fram til posten endrer siden. får komme opp med en smartere løsning senere

**Comment by BobTheShoplifter** [comment]
Slapp en ny fiks nå som er ute på hacs, skal ta direkte kontakt med posten for å se om de kan gi oss et api 😄

**Comment by BMK4560** [comment]
:-)

**Comment by erlendsellie** [comment]
Fikk du kontakt med Posten? Ser de også har funksjonalitet for å vente ut leveringsdager for post i appen sin - sannsynligvis bruker de et annet API der.

**Comment by BobTheShoplifter** [comment]
Spennende! Ikke fått svar fra posten men kan nok intercepte det apiet!! Skal undersøke nå
________________________________

**Comment by BobTheShoplifter** [comment]
Har du screenshot av hvor denne funksjonen er?
________________________________

**Comment by erlendsellie** [comment]
![Screenshot_2023-03-02-13-04-36-66_89a64f02d394bf31c15776f4d11488b4](https://user-images.githubusercontent.com/18458417/222424000-6e99bf19-4e45-49e9-b97a-1ea65b0746bc.jpg)
Nederst på Home Screen i appen. 👍

**Comment by BobTheShoplifter** [comment]
Aha! Ser kanskje ut som det kun har kommet til android så langt? Har ikke android atm så får ikke intercepta før det kommer til ios
________________________________

**Comment by erlendsellie** [comment]
Noen tips til hvordan man kan intercepte det på Android? Gjør du det via nettverket, eller via telefonen?
Kan eventuelt Google litt selv og se om det er en lett sak.

**Comment by BobTheShoplifter** [comment]
Usikker på nye android versjoner, bruker selv burpsuite
________________________________

**Comment by erlendsellie** [comment]
Ser jeg kan capture requests via Postman, om jeg trikser litt mer noen sertifikater og så videre. Skal se om jeg får tatt en titt på det i kveld.

**Comment by BobTheShoplifter** [comment]
Tror jeg fant apiet men det krever auth... https://api.posten.no/mobile-order/distribution-dates?postalCode=7092
