### ISSUE TITLE
Broken after Home Assistant OS 10.1 update

### ISSUE THREAD

**Issue by Chrulf** [BobTheShoplifter/HomeAssistant-Posten#9]
Seems like the integration broke after the new Home Assistant OS 10.1 update.

**Comment by thomas-nesser** [comment]
Lurer på om de virkelig har tenkt å stenge tilgangen nå. Ser de sender med en kp-api-token i header når en kaller:
https://www.posten.no/levering-av-post/_/service/no.posten.website/delivery-days?postalCode=xxxx

og i koden blir kp-api-token satt lik en property .apiKey

Forsøkte å legge inn kp-api-token i header, og da fikk jeg verdier. Men etter noen minutter ble token ugyldig

Kilden er her:
https://www.posten.no/_/service/no.posten.website/react4xp/site/parts/mailbox-delivery/mailbox-delivery.ecadd59343f4a2430166.js

**Comment by BobTheShoplifter** [comment]
Ser de har gjort endringer igjen ja, ekstremt kjedelig av de... Skal se hva jeg får gjort, ser ut som apikeyen genereres av klient

**Comment by BobTheShoplifter** [comment]
![image](https://user-images.githubusercontent.com/22559547/234982712-36e63168-847c-421d-9075-9aab7f99e252.png)
Ser ut til å være en timestamp så burde kunne løse det

**Comment by BobTheShoplifter** [comment]
Prøver å fikse det nå, om posten ødelegger igjen blir jeg direkte lei meg

**Comment by BobTheShoplifter** [comment]
De endra data fra

![image](https://user-images.githubusercontent.com/22559547/235014512-658e8c93-b98e-4ea0-9dcf-66e04db33a60.png)


![image](https://user-images.githubusercontent.com/22559547/235014538-32048a7d-441a-4436-a409-df93911433a5.png)

**Comment by BobTheShoplifter** [comment]
Da skal min bit være fiksa... men https://github.com/ezand/lovelace-posten-card/releases trenger en update. Skal jeg lage en ny version da det ikke ser ut som @ezand støtter denne?


Skal også sies at posten endrer api en ganf i mnd at this point. Vurderer å progge en middleware sånn at endringer går kjappere

**Comment by ggflempire** [comment]
Er det mulig å legge inn noe som converter output fra Posten og gjør den om til feks. det gamle oppsettet ("I dag, Fredag 28 April") eller, holder det sånn det er nå fremover sånn at alle de endringene de driver med ikke endrer output fra sensoren din?

Jeg hadde også en custom sensor som translata det gamle oppsettet og ga en output som kun var "I dag", "I morgen" eller feks. "Mandag". Så jeg lurer bare på om jeg skal prøve å lage en ny for dette nye oppsettet, men hvis posten endrer oppsett igjen om en måned så er det kanskje ikke så mye vits hehe

**Comment by chrissearle** [comment]
Hmm.

Hver gang jeg bruker websiden dems - så får jeg en ny token - og som du sier - så er siste 10 bytes relatert til dagens timestamp.

Men - de første 6 bytes også endre seg fra gang til gang.

Får ikke token som du genere her til å fungere - ei heller hvis jeg bruker den siste jeg fikk for å få de første 6 bytes.

Lurer på om de gjøre noe mere enn "statisk + tid" ?

**Comment by BobTheShoplifter** [comment]
Tokenet har jeg fiksa tror jeg, fant en måte å generere nye hele tiden uten problem.
________________________________

**Comment by chrissearle** [comment]
Det her er rart.

Fikk 400 feil.

Så prøvde jeg det bare i en rest klient - den fikk også 400 feil.

Men - hvis jeg tar å høyre klikk i rest klienten og velg "Copy as cURL" - denne curl kjøring fungerer.

Det skjønner jeg ikke - skal være samme kall.

Men - det ser ut som token er OK - må være kallet et eller annet sted her. Skal se på det videre i kveld - men er nok hos meg feilen ligger .)

**Comment by BobTheShoplifter** [comment]
Her er koden brukt for generering av api key om det hjelper. Super hacky men jeg testa 10t senere og det fungerte fortsatt

```py
import base64
import time

token = (base64.b64encode(bytes(base64.b64decode("f3ccd044MTY4MjYyODE2MQ==")[0:6]) + bytes(str(int(time.time())), "utf8")).decode().replace("=", ""))

print(token)

**Comment by bendikrb** [comment]
Jeg bruker bare en command_line-sensor + en template binary sensor for dette selv, men tenkte jeg kunne dele hvordan jeg har løst det!

```sh
curl -qs "https://www.posten.no/levering-av-post" \
  | grep -oP 'data-react4xp-ref="parts_mailbox-delivery[^{]+\K([^<]+)' \
  | jq -r '"curl -qs -H \"kp-api-token: \(.props.apiKey)\" \"\(.props.serviceUrl)?postalCode=7603\""')

**Comment by bendikrb** [comment]
Jeg bruker bare en command_line-sensor + en template binary sensor for dette selv, men tenkte jeg kunne dele hvordan jeg har løst det!

```sh
curl -qs "https://www.posten.no/levering-av-post" \
  | grep -oP 'data-react4xp-ref="parts_mailbox-delivery[^{]+\K([^<]+)' \
  | jq -r '"curl -qs -H \"kp-api-token: \(.props.apiKey)\" \"\(.props.serviceUrl)?postalCode=7603\""')

**Comment by BobTheShoplifter** [comment]
> Jeg bruker bare en command_line-sensor + en template binary sensor for dette selv, men tenkte jeg kunne dele hvordan jeg har løst det!
> 
> ```shell
> curl -qs "https://www.posten.no/levering-av-post" \
>   | grep -oP 'data-react4xp-ref="parts_mailbox-delivery[^{]+\K([^<]+)' \
>   | jq -r '"curl -qs -H \"kp-api-token: \(.props.apiKey)\" \"\(.props.serviceUrl)?postalCode=7603\""')
> ```

Vi prøver å redusere mengen requests så de ikke blir mer sinte, dette krever 2 fetches mens min "hacky" metode ser ut til å kun kreve 1. Time will tell når ting kommer til posten :(

**Comment by bendikrb** [comment]
> Vi prøver å redusere mengen requests så de ikke blir mer sinte, dette krever 2 fetches mens min "hacky" metode ser ut til å kun kreve 1. Time will tell når ting kommer til posten :(

Er det noen som er sinte..? 🤔

**Comment by BobTheShoplifter** [comment]
> 

Virker sånn ja, de har endret linken litt her og der og adda dette api key systemet kun til dette apiet...

**Comment by bendikrb** [comment]
Hehe.. Det er nok neppe sånn det henger sammen. :)
Ser de har satt rate limit på 60req/s for [postal code-API'et][1] sitt..

.. som jeg fant nå at kanskje er en mer farbar vei!

```bash
curl -qs -H 'x-mybring-api-uid: XXX' -H 'x-mybring-api-key: XXX' https://api.bring.com/address/api/no/postal-codes/7603/mailbox-delivery-dates
```


[1]: https://developer.bring.com/api/postal-code

**Comment by Tikifmb** [comment]
> Er det mulig å legge inn noe som converter output fra Posten og gjør den om til feks. det gamle oppsettet ("I dag, Fredag 28 April") eller, holder det sånn det er nå fremover sånn at alle de endringene de driver med ikke endrer output fra sensoren din?
> 
> Jeg hadde også en custom sensor som translata det gamle oppsettet og ga en output som kun var "I dag", "I morgen" eller feks. "Mandag". Så jeg lurer bare på om jeg skal prøve å lage en ny for dette nye oppsettet, men hvis posten endrer oppsett igjen om en måned så er det kanskje ikke så mye vits hehe

Trengte en ny custom sensor selv. Er ikke så flink med koding så sikkert en bedre måte å gjøre det på, men denne funker for meg:
```
value_template: >-
  {% set next_event = states('sensor.posten_sensor_next') | as_datetime %}
  {% if next_event.date() == now().date() %}
    I dag
  {% elif next_event.date() == (now() + timedelta(days=1)).date() %}
    I morgen
  {% else %}
    {{ next_event.strftime('%A') }}
  {% endif %}  
```

**Comment by ggflempire** [comment]
> > Er det mulig å legge inn noe som converter output fra Posten og gjør den om til feks. det gamle oppsettet ("I dag, Fredag 28 April") eller, holder det sånn det er nå fremover sånn at alle de endringene de driver med ikke endrer output fra sensoren din?
> > Jeg hadde også en custom sensor som translata det gamle oppsettet og ga en output som kun var "I dag", "I morgen" eller feks. "Mandag". Så jeg lurer bare på om jeg skal prøve å lage en ny for dette nye oppsettet, men hvis posten endrer oppsett igjen om en måned så er det kanskje ikke så mye vits hehe
> 
> Trengte en ny custom sensor selv. Er ikke så flink med koding så sikkert en bedre måte å gjøre det på, men denne funker for meg:
> 
> ```
> value_template: >-
>   {% set next_event = states('sensor.posten_sensor_next') | as_datetime %}
>   {% if next_event.date() == now().date() %}
>     I dag
>   {% elif next_event.date() == (now() + timedelta(days=1)).date() %}
>     I morgen
>   {% else %}
>     {{ next_event.strftime('%A') }}
>   {% endif %}  
> ```

Den var ganske lik den jeg lagde. Morsomt å se faktisk. Jeg tok med norsk oversettelse av dagene også. Kan dele min også hvis det er interessant. 

Men. Funker det ikke lengre? Står hos meg at neste postlevering er på fredag 28 april (som var i går...)

{% set next = states("sensor.posten_sensor_next") %}
{% set today = (as_timestamp(now())) | timestamp_custom('%Y-%m-%d') %}
{% set nextDay = (as_timestamp(now()) + (86400)) | timestamp_custom('%Y-%m-%d') %}
{% set dayName=["Mandag","Tirsdag","Onsdag","Torsdag","Fredag","Lørdag", "Søndag"] %}
{% if next == today %}
Post i dag
{% elif next == nextDay %}
Post i morgen
{% else %}
Post på {{dayName[as_timestamp(states("sensor.posten_sensor_next")) | timestamp_custom("%w", true) | int -1]}}
{% endif %}

**Comment by reidarw** [comment]
> Her er koden brukt for generering av api key om det hjelper. Super hacky men jeg testa 10t senere og det fungerte fortsatt
> 
> ```python
> import base64
> import time
> 
> token = (base64.b64encode(bytes(base64.b64decode("f3ccd044MTY4MjYyODE2MQ==")[0:6]) + bytes(str(int(time.time())), "utf8")).decode().replace("=", ""))
> 
> print(token)
> ```

Takk! Dette fikset problemene i Magic Mirror-integrasjonen også.
https://github.com/reidarw/MMM-PostDelivery-Norway

**Comment by BobTheShoplifter** [comment]
Vi kan vurdere å fikse posten card via value_template eller?

**Comment by pvarlien** [comment]
> Vi kan vurdere å fikse posten card via value_template eller?

Hadde vært fint.

**Comment by radhoo2k10** [comment]
Har den sluttet å fungere igjen? 
![image](https://user-images.githubusercontent.com/78762281/236220280-b67c91c9-1439-4093-845c-f0b35a2df389.png)

**Comment by BobTheShoplifter** [comment]
Skal fortsatt fungere.. Ingen log?

**Comment by radhoo2k10** [comment]
Beklager, men det virker nå etter jeg slettet integrasjonen og la den til igjen.

**Comment by uphillbattle** [comment]
Til info: Jeg opplevde det samme som @radhoo2k10 - plutselig (tirsdag 9. mai) sluttet integrasjonen å oppdatere seg. "Last inn integrasjonen på nytt" gjorde bare at sensorene ble utilgjengelig. Samme med restart av HA. Løsningen ble å slette integrasjonen OG slette Posten-komponenten fra HACS. Restarte HA. Installere Posten-komponenten på nytt i HACS og restarte HA. Legge til integrasjonen på nytt. Nå har jeg gode posten-sensorer igjen - så lenge det varer. (Bare slette integrasjonen og legge til på nytt hjalp ikke, jeg måtte også slette Posten-komponenten i HACS og legge til på nytt.)

**Comment by radhoo2k10** [comment]
Der forsvant sensorene igjen. Vet ikke om dette sier deg noe:
`2023-05-10 19:38:01.568 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up posten platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 653, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/binary_sensor.py", line 49, in icon
    nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'
2023-05-10 19:38:01.571 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up posten platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 653, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/sensor.py", line 31, in icon
    nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'
2023-05-10 19:38:59.251 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform posten
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 653, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/binary_sensor.py", line 49, in icon
    nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'
2023-05-10 19:38:59.257 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform posten
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 653, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/sensor.py", line 31, in icon
    nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'
2023-05-10 19:38:59.265 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up posten platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 653, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/binary_sensor.py", line 49, in icon
    nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'
2023-05-10 19:38:59.270 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up posten platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 653, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/posten/sensor.py", line 31, in icon
    nextdelivery = self.coordinator.data.get("delivery_dates")
AttributeError: 'list' object has no attribute 'get'`

Er ikke stødig med å ordne logger i HA da jeg aldri har gjort det før. Hvis du har behov for bedre log, så trenger jeg en liten teskje guide om hvordan jeg gjør det.

**Comment by BobTheShoplifter** [comment]
Jeg mistenker at det er 10% sjanse ellerno posten returnerer et tomt objekt basert på min fiks. (Typ en Edge case med spesifikke sekunder) jeg tror jeg skal implementere en retry som prøver 3 ganger evt en backupløsning
________________________________

**Comment by uphillbattle** [comment]
> Til info: Jeg opplevde det samme som @radhoo2k10 - plutselig (tirsdag 9. mai) sluttet integrasjonen å oppdatere seg. "Last inn integrasjonen på nytt" gjorde bare at sensorene ble utilgjengelig. Samme med restart av HA. Løsningen ble å slette integrasjonen OG slette Posten-komponenten fra HACS. Restarte HA. Installere Posten-komponenten på nytt i HACS og restarte HA. Legge til integrasjonen på nytt. Nå har jeg gode posten-sensorer igjen - så lenge det varer. (Bare slette integrasjonen og legge til på nytt hjalp ikke, jeg måtte også slette Posten-komponenten i HACS og legge til på nytt.)

Etter at jeg i går meldte om at jeg løste problemet ved å av- og ny-installere posten-komponenten i HACS, stoppet integrasjonen på nytt å oppdatere seg. Vet ikke om det er til hjelp, men dette ser jeg i HA-loggene:

``` 
2023-05-11 12:14:16.413 ERROR (MainThread) [custom_components.posten] f3ccd044MTY4MzgwMDA1Ng
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
File "/config/custom_components/posten/binary_sensor.py", line 38, in is_on
```

**Comment by BobTheShoplifter** [comment]
Spennende! Skal undersøke dette, virker som posten gjør det vanskelig :(
________________________________

**Comment by BobTheShoplifter** [comment]
Vi fant en fiks nå!

**Comment by radhoo2k10** [comment]
Nydelig. Laster inn ny versjon så fort den er klar!
